version: '3'
services:
  neo4j:
    container_name: neo4j
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j_data:/data
    environment:
      NEO4J_AUTH: none

volumes:
  neo4j_data:

